### ISSUE TITLE
Epic: automate backport handling

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/releases#139]
We now maintain stable branches, but when backports are needed they are being handled manually. I propose to look at what it would take to automate the process of backporting commits, and if there are any existing tools we can leverage for that.

- [x] Document the backport process: https://github.com/submariner-io/submariner-website/issues/521
- [x] Automate backport process https://github.com/submariner-io/shipyard/pull/618
- [x] Document automated backport process https://github.com/submariner-io/submariner-website/pull/580

**Comment by mkolesnik** [comment]
FYI a couple of interesting patents we can consider to use here:

* https://patents.google.com/patent/US9606793B1/en
* https://patents.google.com/patent/US20200257597A1/en
